# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import reddit_pb2 as protos_dot_reddit__pb2


class RedditServiceStub(object):
    """Define the service with RPC methods
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePost = channel.unary_unary(
                '/myapp.RedditService/CreatePost',
                request_serializer=protos_dot_reddit__pb2.CreatePostRequest.SerializeToString,
                response_deserializer=protos_dot_reddit__pb2.CreatePostResponse.FromString,
                )
        self.VotePost = channel.unary_unary(
                '/myapp.RedditService/VotePost',
                request_serializer=protos_dot_reddit__pb2.VotePostRequest.SerializeToString,
                response_deserializer=protos_dot_reddit__pb2.VoteResponse.FromString,
                )
        self.GetPost = channel.unary_unary(
                '/myapp.RedditService/GetPost',
                request_serializer=protos_dot_reddit__pb2.GetPostRequest.SerializeToString,
                response_deserializer=protos_dot_reddit__pb2.Post.FromString,
                )
        self.CreateComment = channel.unary_unary(
                '/myapp.RedditService/CreateComment',
                request_serializer=protos_dot_reddit__pb2.CreateCommentRequest.SerializeToString,
                response_deserializer=protos_dot_reddit__pb2.CreateCommentResponse.FromString,
                )
        self.VoteComment = channel.unary_unary(
                '/myapp.RedditService/VoteComment',
                request_serializer=protos_dot_reddit__pb2.VoteCommentRequest.SerializeToString,
                response_deserializer=protos_dot_reddit__pb2.VoteResponse.FromString,
                )
        self.GetTopComments = channel.unary_unary(
                '/myapp.RedditService/GetTopComments',
                request_serializer=protos_dot_reddit__pb2.GetTopCommentsRequest.SerializeToString,
                response_deserializer=protos_dot_reddit__pb2.TopCommentsResponse.FromString,
                )
        self.ExpandCommentBranch = channel.unary_unary(
                '/myapp.RedditService/ExpandCommentBranch',
                request_serializer=protos_dot_reddit__pb2.ExpandCommentBranchRequest.SerializeToString,
                response_deserializer=protos_dot_reddit__pb2.CommentBranchResponse.FromString,
                )


class RedditServiceServicer(object):
    """Define the service with RPC methods
    """

    def CreatePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VotePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VoteComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopComments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExpandCommentBranch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RedditServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePost,
                    request_deserializer=protos_dot_reddit__pb2.CreatePostRequest.FromString,
                    response_serializer=protos_dot_reddit__pb2.CreatePostResponse.SerializeToString,
            ),
            'VotePost': grpc.unary_unary_rpc_method_handler(
                    servicer.VotePost,
                    request_deserializer=protos_dot_reddit__pb2.VotePostRequest.FromString,
                    response_serializer=protos_dot_reddit__pb2.VoteResponse.SerializeToString,
            ),
            'GetPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPost,
                    request_deserializer=protos_dot_reddit__pb2.GetPostRequest.FromString,
                    response_serializer=protos_dot_reddit__pb2.Post.SerializeToString,
            ),
            'CreateComment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateComment,
                    request_deserializer=protos_dot_reddit__pb2.CreateCommentRequest.FromString,
                    response_serializer=protos_dot_reddit__pb2.CreateCommentResponse.SerializeToString,
            ),
            'VoteComment': grpc.unary_unary_rpc_method_handler(
                    servicer.VoteComment,
                    request_deserializer=protos_dot_reddit__pb2.VoteCommentRequest.FromString,
                    response_serializer=protos_dot_reddit__pb2.VoteResponse.SerializeToString,
            ),
            'GetTopComments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopComments,
                    request_deserializer=protos_dot_reddit__pb2.GetTopCommentsRequest.FromString,
                    response_serializer=protos_dot_reddit__pb2.TopCommentsResponse.SerializeToString,
            ),
            'ExpandCommentBranch': grpc.unary_unary_rpc_method_handler(
                    servicer.ExpandCommentBranch,
                    request_deserializer=protos_dot_reddit__pb2.ExpandCommentBranchRequest.FromString,
                    response_serializer=protos_dot_reddit__pb2.CommentBranchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myapp.RedditService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RedditService(object):
    """Define the service with RPC methods
    """

    @staticmethod
    def CreatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myapp.RedditService/CreatePost',
            protos_dot_reddit__pb2.CreatePostRequest.SerializeToString,
            protos_dot_reddit__pb2.CreatePostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VotePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myapp.RedditService/VotePost',
            protos_dot_reddit__pb2.VotePostRequest.SerializeToString,
            protos_dot_reddit__pb2.VoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myapp.RedditService/GetPost',
            protos_dot_reddit__pb2.GetPostRequest.SerializeToString,
            protos_dot_reddit__pb2.Post.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myapp.RedditService/CreateComment',
            protos_dot_reddit__pb2.CreateCommentRequest.SerializeToString,
            protos_dot_reddit__pb2.CreateCommentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VoteComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myapp.RedditService/VoteComment',
            protos_dot_reddit__pb2.VoteCommentRequest.SerializeToString,
            protos_dot_reddit__pb2.VoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTopComments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myapp.RedditService/GetTopComments',
            protos_dot_reddit__pb2.GetTopCommentsRequest.SerializeToString,
            protos_dot_reddit__pb2.TopCommentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExpandCommentBranch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myapp.RedditService/ExpandCommentBranch',
            protos_dot_reddit__pb2.ExpandCommentBranchRequest.SerializeToString,
            protos_dot_reddit__pb2.CommentBranchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
